services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'cardapio_redis_data:/bitnami/redis/data'

volumes:
  cardapio_redis_data: {}